### ISSUE TITLE
无法保存插件,难道是多了吗？

### ISSUE THREAD

**Issue by xbdsky** [mkanako/chrome-ext-box#1]
视频演示地址 https://cl.ly/3k3s2p2A2u07

**Comment by mkanako** [comment]
哇，你这个确实有点多啊，找起来估计都麻烦
我刚刚测试了下添加60个进去也都没问题，重现不了这个问题，看看控制台有没有报错之类的？

**Comment by xbdsky** [comment]
貌似是有的可以添加，有的就不行，没看到报错的

**Comment by mkanako** [comment]
噢，又测了一下，大概50几个就报错了，上午没看细，原因是数据太多，万万没想到啊 😂
这个扩展使用chrome.storage.sync接口存储数据，查了下它对单个选项数据限制是8,192 bytes，超过了就报错数据插不进去

不过我实际添加进去也就十来个，不会像你这么多啊，而且这么多图标，你用的时候找也找半天啊看着都眼花啊，如果你想把你所有扩展都添加进去，那其实有其他的扩展管理更适合你，你觉得呢

**Comment by mkanako** [comment]
看了下，数据里面包含了图标链接，这个占主要的数据量，那么可以稍微改下不保存这个图标链接，这样就能保存更多数据了😬

**Comment by xbdsky** [comment]
恩，比较喜欢倒腾，加的比较，看到你这个挺不错的，就用了呢，万一其他人也有这样的需求呢，哈哈，您要是有时间的话，能可以更新下哦，哈哈，不过真的很感谢您开发这么好用的软件。

**Comment by mkanako** [comment]
已解决
